### ISSUE TITLE
Migrate Project to Openshift v0.5.x & Fabric8

### ISSUE THREAD

**Issue by cmoulliard** [christian-posta/ceposta-devops-ose#15]
Gerrit
- [x] Gerrit user (jenkins, reviewer, ...) #16 
- [x] Gerrit Project access settings #17 

Jenkins
- [x] Jenkins Kube App & Docker Container #18 
- [x] Compare list of jenkins plugins (christian vs fabric8) #20
- [x] Compare maven settings jenkins (christian vs fabric8) #21
- [ ] Compare config.xml of jenkins (christian vs fabric8) #22
- [ ] What should be the jobs that we will propose when jenkins docker is created #23 
- [ ] Can we use the Fabric8 Nexus Kube App & Docker Container #24 

Karaf
- [ ] Howto build the demo/quickstart project part of the CD scenario #19
